name: Windows-RDP-Custom-Password

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Install Brave Browser
      shell: pwsh
      run: |
        $url = "https://laptop-updates.brave.com/latest/winx64"
        Invoke-WebRequest -Uri $url -OutFile "D:\BraveSetup.exe"

        Start-Process "D:\BraveSetup.exe" -ArgumentList "/silent /install" -Wait

    - name: Setup Tailscale VPN
      shell: pwsh
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
        Start-Process -FilePath ".\tailscale.exe" -ArgumentList "/quiet" -Wait

    - name: Connect Tailscale
      shell: pwsh
      run: |
        Start-Service -Name tailscaled -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 5

        $tailscalePath = "C:\Program Files\Tailscale\tailscale.exe"

        Start-Process -FilePath $tailscalePath `
        -ArgumentList "up --auth-key ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-rdp" `
        -Wait

    - name: Enable RDP + Password Setup
      shell: pwsh
      run: |
        Set-ItemProperty `
        -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
        -Name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty `
        -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\Rdp-Tcp' `
        -Name "UserAuthentication" -Value 1

        $Password = ConvertTo-SecureString "Adynr17@" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $Password

    - name: Fast Remove Visual Studio
      shell: pwsh
      run: |
        $paths = @(
            "C:\Program Files\Microsoft Visual Studio",
            "C:\ProgramData\Microsoft\VisualStudio"
        )

        foreach ($p in $paths) {
            if (Test-Path $p) {
                Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
            }
        }

    - name: Keep Alive 6 Hours
      shell: pwsh
      run: |
        $end_time = (Get-Date).AddHours(6)

        while ((Get-Date) -lt $end_time) {
            Write-Host "RDP Aktif..."
            Start-Sleep -Seconds 60
        }
